Module7 task1
htmlacademy-react/1812645-six-cities-8 pull request #10
Opened 2021-11-09 20:12 UTC by lgmarch

2021-11-10 19:48 UTC, slyvkanychmykyta requested changes

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/components/forms/sorting-form/sorting-form.tsx
> +  sortBy: state.DISPLAY_SETTINGS.sort,
а почему сделала snake case'ом? Раньше выглядело лучше

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/components/pages/loading-screen/loading-screen.tsx
> +function LoadingScreen(): JSX.Element {
у тебя в папке pages лежат компоненты без дополнительной приставки -screen или -page. Логично будет добавить всем страницам приставку -page, так как они лежат в директории /pages

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/components/pages/main/main.tsx
> +                            We could not find any property available at the moment in Dusseldorf
вместо dusseldorf нужно указать конкретный город

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/components/pages/sign-in/login.tsx
> +import React from 'react';
а зачем добавила import реакта? В версии начиная с 17 можно не импортировать его

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/services/token.ts
> +  const token = localStorage.getItem(AUTH_TOKEN_KEY_NAME);
действия с local storage лучше оборачивать в try..catch и сериализовать и десиреализовать токен ( с помощью JSON.stringify, JSON.parse)

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/store/reducers/offers.ts
> +    convertPropertiesOfOffers(action.payload);
так делать не нужно, ты ведь мутируешь объект. Тебе нужно возвращать новый

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/utils/transformProperties.ts
> +export function convertPropertiesOfOffers(offers: PlaceCardType[]): void {
Все эти хелперы не нужны. Это очень сложно написано, мапперы следует писать индивидуально под каждый запрос, твой mapper должен выгдядеть  примерно таким образом: 
```
const mapOffers(backendResponse): (тип результрующего объекта) => ({
  city: backendResponse.city,
  isFavorite: backendResponse.is_Favorite,
...
})
```
Т.е это по сути перебор свойств пришедших с сервера в новый вид. Аналогично делается при запросе POST на сервер. В таком случае будет понятен перечень всех свойств, которые возвращает сервер, и всем будет удобно пользоваться такими данными

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/types/action-type.ts
> +  LoadOffers = 'data/loadOffers',
тут скорее setOffers, потому что они уже сетятся после загрузки

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/types/store-type.ts
> +  authStatus: AuthorizationStatus,
статус аутентификации никак не относится к настройкам, его лучше вынести в отдельный редьюсер

2021-11-10 19:48 UTC, slyvkanychmykyta commented on project/src/types/store-type.ts
> +  isDataLoaded: boolean,
а этот статус должен лежать в том же стейте, что и сами данные, т.е в offers

2021-11-10 21:29 UTC, lgmarch commented on project/src/components/pages/sign-in/login.tsx
> +import React from 'react';
Никита, да у меня Шторм (при переходе на старую версию) варнинги стал выдавать. Уберу...

2021-11-10 21:37 UTC, lgmarch commented on project/src/types/store-type.ts
> +  authStatus: AuthorizationStatus,
Да, я именно так и сделала с домашке 7.2.

2021-11-10 21:38 UTC, lgmarch commented on project/src/types/store-type.ts
> +  isDataLoaded: boolean,
Да, в 7.2 перенесла.

2021-11-11 18:32 UTC, slyvkanychmykyta requested changes

2021-11-11 18:32 UTC, slyvkanychmykyta commented on project/src/services/token.ts
>  export const getToken = (): Token => {
ты же создала вспомогательную функцию для работы со стореджем, вот ее и нужно тут использовать)

2021-11-11 18:32 UTC, slyvkanychmykyta commented on project/src/utils/transformProperties.ts
> +export function mapOffers(backendResponse: PlaceCardType[]): PlaceCardType[] {
`export const mapOffers (backendResponse) => {
     return backendResponse.map(mapOffer);
}`
где mapOffer - функция которая мапит один объект, т.е 
`const mapOffer = (offerBack: {'is_favorite': boolean}):PlaceCardType => ({
  isFavorite: offerBack?.is_favorite,
});` (.? - это optional chaining, в случае если поле с бэкенда не пришло, то будет undefined)

2021-11-11 18:32 UTC, slyvkanychmykyta commented on project/src/services/token.ts
> +  return String(token);
с локал стореджа и так возвращается string, если использовать хелпер

2021-11-11 18:32 UTC, slyvkanychmykyta commented on project/src/store/action.ts
> +export const loadOffers = (allOffers: PlaceCardTypeBackend[]) => ({
просто `offer[]`

2021-11-11 18:32 UTC, slyvkanychmykyta commented on project/src/types/place-card-type.ts
> +  id: number,
лучше все поля бэкендовые оборачивать в скобки, будет лучше смотреться

2021-11-11 19:52 UTC, lgmarch commented on project/src/services/token.ts
> +  return String(token);
Ругается, почему-то. Просит string

2021-11-11 20:42 UTC, merged